/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/ExaminationDetails': RouteRecordInfo<'/ExaminationDetails', '/ExaminationDetails', Record<never, never>, Record<never, never>>,
    '/IlnessDetails': RouteRecordInfo<'/IlnessDetails', '/IlnessDetails', Record<never, never>, Record<never, never>>,
    '/landingPage': RouteRecordInfo<'/landingPage', '/landingPage', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/patientDetails': RouteRecordInfo<'/patientDetails', '/patientDetails', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/RegisterPatient': RouteRecordInfo<'/RegisterPatient', '/RegisterPatient', Record<never, never>, Record<never, never>>,
    '/YourPatients': RouteRecordInfo<'/YourPatients', '/YourPatients', Record<never, never>, Record<never, never>>,
  }
}
